package main.usecase.eventing;

public enum Predicate {
    ACCOUNTS_LOADED,
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    ACCOUNT_SELECTED,
    CURRENT_BALANCE_UPDATED,
    LAYOUT_ALERT,
    TRANSACTION_ISSUED,
    TRANSACTION_SERIES_ISSUED,
    TRANSACTIONS_LOADED
}
