package main.usecase.eventing;

public enum Predicate {
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    ACCOUNT_SELECTED,
    CURRENT_BALANCE_UPDATED,
    TRANSACTION_ISSUED,
    TRANSACTION_SERIES_ISSUED,
}
