package main.usecase.eventing;

public enum Predicate {
    ACCOUNTS_LOADED,
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    ACCOUNT_SELECTED,
    ACTION_TAKEN,
    BET_PLACED,
    CURRENT_BALANCE,
    LAYOUT_ALERT,
    LAYOUT_CHANGED,
    TRANSACTION,
    TRANSACTION_SERIES,
    TRANSACTIONS_LOADED
}
