package main.usecase;

public enum NetworkElement {
    ACCOUNTS_LOADED,
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    BET_PLACED,
    CURRENT_BALANCE,
    TRANSACTION,
    TRANSACTION_SERIES,
    TRANSACTIONS_LOADED
}
