package main.usecase;

public enum Predicate {
    ACCOUNTS_LOADED,
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    ACTION_TAKEN,
    BET_PLACED,
    CURRENT_BALANCE,
    TRANSACTION,
    TRANSACTION_SERIES,
    TRANSACTIONS_LOADED
}
