package main.usecase;

public enum Predicate {
    ACCOUNTS_LOADED,
    ACCOUNT_DELETED,
    ACCOUNT_OPENED,
    ACTION_TAKEN,
    BALANCE_UPDATED,
    BET_PLACED,
    GAME_STATE_CHANGED,
    LAYOUT_CHANGED,
    TRANSACTIONS_LOADED
}
